#!/bin/sh

# Enable VNC clipboard
vncconfig -iconic &

# Set X window background
xsetroot -solid grey

# Run X window manager
x-window-manager &

# Run Gnome desktop
metacity &
gnome-panel &
gnome-session &
